name: Publish GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Convert Markdown into HTML and PDF (ja)
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          config-file: ./contents/.marprc.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./contents
